# Generated by Django 6.1 on 2026-09-07 20:17

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model("trips", "Category")

    categories = [
        {"description": "Trabalho"},
        {"description": "Atividade física"},
        {"description": "Lazer"},
        {"description": "Deslocamento"},
    ]

    for c in categories:
        Category.objects.get_or_create(description=c["description"])

class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories)
    ]
