# Generated by Django 6.1 on 2026-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20260907_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(choices=[('work', 'Work'), ('exercise', 'Exercise'), ('leisure', 'Leisure'), ('commuting', 'Commuting')], default='exercise', max_length=255, unique=True),
        ),
    ]
