# Generated by Django 6.1 on 2026-09-09 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_status'),
        ('trips', '0003_alter_category_options_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bike',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='bikes.bike'),
        ),
    ]
