# Generated by Django 6.1 on 2026-09-13 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_city'),
        ('trips', '0004_trip_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='finish_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_ended', to='stations.station'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_station',
            field=models.ForeignKey(default='01a09c42-8d62-71ad-a615-ede028ae6c9a', on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_started', to='stations.station'),
            preserve_default=False,
        ),
    ]
