# Generated by Django 6.1 on 2026-09-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
