# Generated by Django 6.1 on 2026-09-09 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('electric', 'Electric'), ('mechanic', 'Mechanic')], default='mechanic', max_length=254)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='stations.station')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
