# Generated by Django 6.1 on 2026-09-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In use'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], default='unknown', max_length=254),
        ),
    ]
