# Generated by Django 6.1 on 2026-09-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_status'),
        ('stations', '0002_station_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='stations.station'),
        ),
    ]
